### ISSUE TITLE
effects being auto created when I right click on token

### ISSUE THREAD

**Issue by MrPotatoZed** [p4535992/foundryvtt-lights-hud-ate#12]
* Foundry VTT Version: 2.692
* Operating System: Windows 10
* How Are You Using Foundry: firefox and chrome, hosted on the forge
* Which Game System:  5e 1.6.2
* Modules Enabled?: LightsHUD and dependencies only 

When I right click on token it's creating a bunch of inactive effects. When I try to delete them they are returning. I'm also not able to pull up the token menu by clicking on the cog icon in the hud. See video below. I am seeing errors in console. See pic below. This was not happening when I started testing with this token so I presume it's something to do with adding/removing various items on the same token. 
![image](https://user-images.githubusercontent.com/85974617/173254998-0098773e-4675-4e37-85b6-107e005b4468.png)
![lightshud](https://user-images.githubusercontent.com/85974617/173255037-d6339436-c6ca-4b99-ad4f-35fd5d016ad0.gif)

Active modules:
![image](https://user-images.githubusercontent.com/85974617/173255128-72a86fd8-4388-45bf-80f7-4f934d21665e.png)

**Comment by p4535992** [comment]
Try out 0.11.24, i disable by default the "auto apply effect" feature, never see that issue before.

**Comment by MrPotatoZed** [comment]
In .11.24 an effect was applied when I added items from the ATE compendium to an inventory but that's because they were set to transfer effect to actor on item equip in the effects menu. Turned that off and can confirm it is no longer adding effects when I click the light button in the hud. Thanks for looking at it.
