### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Orionox** [p4535992/foundryvtt-lights-hud-ate#2]
**Module Version:** v0.118

**Describe the bug**
The HUD element is not showing up for a specific character. It was a character that I was troubleshooting bugs for LightHUD (OG) with. 

**To Reproduce**
I do not know how to reproduce it, but it is only affecting one of my tokens. Every other token is working correctly

**Expected behavior**
The HD element for lightHUD +ATE shold show up in the token HD

**Screenshots**

![Capture](https://user-images.githubusercontent.com/20059838/166497185-1c36851a-e7a2-4bfb-80fe-a1c049035245.PNG)

**Comment by p4535992** [comment]
Should be solved with 0.11.9
