### ISSUE TITLE
Range of lights (feet / meters)

### ISSUE THREAD

**Issue by Kariaudhanaur** [p4535992/foundryvtt-lights-hud-ate#4]
I'm discovering your module (automatic update from Lights Hud), but could it be possible to have "standard lights with meters as unit" ? 
Because as it is now... Nothing works properly for me haha... My scene are in meters, so obviously range of lights are way to big... 
Is it possible to add some module options about the units ? 
Or do I have to create each "vision" / "lights" myself ? 
Thank you anyway !

**Comment by p4535992** [comment]
Try out 0.11.10 i add a module settings for apply metric distance for the preset light and vision, you can still set up a custom light ot vision with the advanced dailog form if you need something more specific.

**Comment by Kariaudhanaur** [comment]
I haven't tested all distance, but the ones I've tested are ok ! Thank you very very much :)
