### ISSUE TITLE
[BUG] Token hud button is missing on token

### ISSUE THREAD

**Issue by VaethConner** [p4535992/foundryvtt-lights-hud-ate#5]
**Module Version:** v0.11.8

**Describe the bug**
Light hub icon on token is missing, but is still available on other tokens
**To Reproduce**
1.Right click token
2. Button missing

**Expected behavior**
The button should be there for the token but it's not there

**Screenshots**
![image](https://user-images.githubusercontent.com/47077661/167316610-7f8c8fd6-6a56-4dce-be22-d51d3ce12952.png)
![image](https://user-images.githubusercontent.com/47077661/167316623-7cfdd5e4-fe7f-47c5-93e1-9d2166466a24.png)

**Browser:**
 -  Foundry

**Foundry Version:**  
V9.269

**Game System:** 
Dnd 5e 1.6.1

**Additional context**
Any solution to this? Am I missing something that this particular token is missing the hud button?

**Comment by p4535992** [comment]
Maybe is a unlinked token ?
Click F12 on the browse and tell me if you see any "red message" when you right click that token

**Comment by VaethConner** [comment]
![image](https://user-images.githubusercontent.com/47077661/167449542-85f28d41-abe4-4676-a8e3-3f96d36a49b3.png)
[fvtt-Actor-nili.zip](https://github.com/p4535992/foundryvtt-lights-hud-ate/files/8653306/fvtt-Actor-nili.zip)

**Comment by p4535992** [comment]
@VaethConner  use the last release v0.11.10 should be already solved

**Comment by VaethConner** [comment]
Awesome it works now! Thanks!
