### ISSUE TITLE
[BUG] Message Updating

### ISSUE THREAD

**Issue by brunocalado** [p4535992/foundryvtt-lights-hud-ate#7]
Every time I press update I got this message
![image](https://user-images.githubusercontent.com/4999783/169536958-e71cdcf0-1cd7-495f-8808-9b815ddbb9f6.png)

**Comment by p4535992** [comment]
That's is "LightHUD" not "LightHUD+ATE" these are two different module.
My advise is to unistall "LightHUD" and use "LightHUD+ATE" the official successor.
