### ISSUE TITLE
[BUG] Auto-launch a DAE effect with the Lights-hud-ate 

### ISSUE THREAD

**Issue by Fridan99** [p4535992/foundryvtt-lights-hud-ate#9]
**Module Version:** v0.11.16
DAE 0.10.16
Foundry VTT v9. build 269
System Dnd 5e 1.6.1

**Describe the bug**
After the recent update of the ATE, it happens to me that when I right click on an actor token, to display the hud, automatically launches a dae effect without doing anything else. 

**To Reproduce**
1. Go to 'the actor'
2. Right Click on 'it'

**Expected behavior**
See the hud as normal, without launch a dae effect 

**Screenshots**
![track4](https://user-images.githubusercontent.com/86131373/171287104-dff32d4a-5b73-4f04-9a75-f8caf42494d8.jpg)

**Browser:** native App
 - 

**Additional context**
Add any other context (like other modules installed) about the problem here.

A copy of the actor to test the problem. That actor has 2 img as token mold (when use the DAE effect of Radiant Soul, it changes to another img). **Apparently the new ATE update makes it run automatically by right clicking on the token to display the HUD.** 

Download the actor .json
https://easyupload.io/kmv6jg

When i disable the ATE, all works normally again. 

Video reproducing the problem.

https://user-images.githubusercontent.com/86131373/171288320-f05b8375-0685-41cf-b31d-78e0dd813524.MOV

**Comment by Fridan99** [comment]
For some reason every time I update the ATE, it updates between 0.11.8 and 0.11.16. 

I mean 
if I have the 0.11.8 is updated to 0.11.16
if I have 0.11.16, it updates to 0.11.8.

This happens every time I update Foundry modules in bulk. I always update the ATE to one or another version. 
![track0](https://user-images.githubusercontent.com/86131373/171676311-2a3da3d5-7def-4327-8527-c05bff3b53b4.jpg)

**Comment by p4535992** [comment]
@Fridan99 i can't replicate the error what dae effect is automatically launched ? Is **Radiant Soul** ?

_A question the issue still persist if you don't use a wildcard image for that token ?_

i can't replicate the manifest bug either, i create a new release for force a refresh of the cache on your side try out a new update.

**Comment by Fridan99** [comment]
Yes... the Radiant Soul

I haven't tried it without a wildcard image... when I'm at home I'll try it.

**Comment by Fridan99** [comment]
If i remove the random img on the token, and only use 1 img.... the problem persist. I also remove the DAE effect of change the img, and the problem persist.... it auto-launch the DAE effect of scale 3. 

Console with the copy token (no alternative img, no DAE scale 3 effect)
![track3](https://user-images.githubusercontent.com/86131373/172061577-2b6cf58d-a771-4149-ba8e-4db50ac61884.jpg)

Console with the original token (alternative img, and DAE effects)
![track4](https://user-images.githubusercontent.com/86131373/172061587-e2cc3deb-e671-409a-b403-3d9d9313327d.jpg)

**Comment by Fridan99** [comment]
The strange thing is that it detects the Radiant Soul as an ATE effect, and checking the Radiant Soul (it does not have any type of DAE or similar illumination effect).
![track5](https://user-images.githubusercontent.com/86131373/172062137-eba9d42f-278d-4741-8dec-e24d35de0740.jpg)
![track6](https://user-images.githubusercontent.com/86131373/172062139-442b60c9-322a-42a4-8f82-ca92790db8d1.jpg)

**Comment by p4535992** [comment]
_The strange thing is that it detects the Radiant Soul as an ATE effect, and checking the Radiant Soul (it does not have any type of DAE or similar illumination effect)._

That is normal the filter is just for the ATL key, so any active effects with thata key is detect as ATE

**Comment by p4535992** [comment]
@Fridan99  _For some reason every time I update the ATE, it updates between 0.11.8 and 0.11.16._ this is to strange nobody is been reporting this... are you sure the version you see is 0.11.16/8 and not 0.11.17 ? 
Try to unistall and reinstal the module. i don't know about this , but the last releas eis 0.11.17.

**Comment by Fridan99** [comment]
> 

now I get 0.11.17.... I have tried to update several times and this error DOES NOT occur anymore, as for 0.11.16/8

**Comment by p4535992** [comment]
i am happy for you, let me know if you find any other errors.
Now that you have pointed this out to me in the next release, I will put in a filter for non-lighting related ATL effects.

**Comment by Fridan99** [comment]
It's strange.... the bug seems to persist... now compile between 0.11.17 and 0.11.8

I leave you a video of the whole upgrade process..... the link below

https://easyupload.io/20pqxn

(min 01:45 to see the final update)
I have tried uninstalling and installing the ATE, but it does not fix the error. 

Could it be some kind of conflict with the other module name LightsHUD and LightsHUD+ATE? Because of the similar name?

It's strange, but whenever I mass update, these 2 modules are always updated, LightsHUD compiles between 0.10.8 and 0.10.8g.

**Comment by Fridan99** [comment]
It's strange... I uninstalled LightsHUD and ATE now doesn't compile.... it shouldn't (as far as I understand). Coincidence?

**Comment by Fridan99** [comment]
By the way, the auto-launch bug of the DAE effect is still in 0.11.17

**Comment by p4535992** [comment]
What did you mean _"is not compile"_ ?

NO they are two separate module:

**LightsHUD** is a module with id "lights-hud". 
**LightsHUD + ATE** is another module with id "lights-hud-ate", but with dependencies to ATE (you can read that on the module management)
**ATE** is another module with id "ATL" used as dependencies

So you can install **LightsHUD** without **ATE**, but you can't install **LightsHUD+ATE** without **ATE**

When you start the program on windows you start it as administrator right? It could be a disk writinng permission problem the updating bug.

**Comment by Fridan99** [comment]
When i say compile i mean Switching from one to the other and vice versa (0.11.17 and 0.11.8)

Nop, i never start as an administrator when i update modules…. only when update the app.

should i enter as an administrator when try to update modules?

i have the ATE (and its dependencies) and the LightsHUD+ATE as well, obiously 🤣

**Comment by p4535992** [comment]
try ou to run the app as administrator , it can be a writing permission on the disk.

**Comment by Fridan99** [comment]
In fact I just deleted LightsHUD+ATE right now and tried to install LightsHUD, and it installs LightsHUD+ATE in v 0.11.8.

**Comment by Fridan99** [comment]
With the recent update 0.11.21, the DAE effect of the Radiant Soul is now enabled and disabled. 

I have already discovered the problem, disabling LightsHUD+ATE or the DFreds Effects Panel module fixes it. 

So the problem is some incompatibility with those modules.

**Comment by p4535992** [comment]
try out 0.11.22

**Comment by Fridan99** [comment]
> try out 0.11.22

It seems that the DAE effect is no longer auto-executing. But there is still some kind of error. Even if the effect itself does not autorun, the icon effect appears in the DF Effects Panel as if it had been executed. Strange. 

Uploading Video test 2.mp4…

**Comment by Fridan99** [comment]
It seems that with 0.11.24 the problem has been solved. You are a genius.

:)

**Comment by p4535992** [comment]
Take me four release for solve the problem...so not really a genius...
